CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT UNIQUE NOT NULL,
	hashed_password TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE events (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	organizer_id INTEGER NOT NULL,
	state TEXT DEFAULT 'eventCreated' NOT NULL,
	name TEXT NOT NULL,
	proposed_date TEXT NOT NULL,
	finalized_email_text TEXT,
	finalized_ics_file TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (organizer_id) REFERENCES users(id)
);

CREATE TABLE invitees (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	event_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	availability_sent BOOLEAN NOT NULL DEFAULT FALSE,
	availability_response TEXT,
	finalized_date_sent BOOLEAN NOT NULL DEFAULT FALSE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (event_id) REFERENCES events(id),
	FOREIGN KEY (user_id) REFERENCES users(id)
);
