CREATE TABLE users (
	id VARCHAR NOT NULL,
	email VARCHAR UNIQUE NOT NULL,
	hashed_password VARCHAR,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE events (
	id VARCHAR NOT NULL,
	organizer_id VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	proposed_date VARCHAR NOT NULL,
	finalized_date VARCHAR,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (organizer_id) REFERENCES users(id)
);

CREATE TABLE invitees (
	id VARCHAR NOT NULL,
	event_id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	invite_sent BOOLEAN NOT NULL DEFAULT FALSE,
	response VARCHAR,
	finalized_date_sent BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (event_id) REFERENCES events(id),
	FOREIGN KEY (user_id) REFERENCES users(id)
);

